#ifndef SETTINGS_H
#define SETTINGS_H

#define FONT_COUNT 5

const uint32_t BIG_FONTS[] = {
	RESOURCE_ID_FONT_AUDIOWIDE_48,
	RESOURCE_ID_FONT_SPECIAL_ELITE_48,
	RESOURCE_ID_FONT_CAESAR_DRESSING_48,
	RESOURCE_ID_FONT_UNIFRAKTUR_MAGUNTIA_48,
	RESOURCE_ID_FONT_UBUNTU_MONO_48
};

const uint32_t SMALL_FONTS[] = {
	RESOURCE_ID_FONT_AUDIOWIDE_24,
	RESOURCE_ID_FONT_SPECIAL_ELITE_24,
	RESOURCE_ID_FONT_CAESAR_DRESSING_24,
	RESOURCE_ID_FONT_UNIFRAKTUR_MAGUNTIA_24,
	RESOURCE_ID_FONT_UBUNTU_MONO_24
};

#define HEADER_BOUNDS GRect(0, 10, 144, 30)
#define HEADER_TEXT "L3 M1l0nkh"

#define TIME_FONT RESOURCE_ID_FONT_UBUNTU_MONO_48
#define TIME_X 0
#define TIME_Y_NORMAL 52
#define TIME_Y_ROUND 58
#define TIME_HEIGHT 50

#define DATE_FONT RESOURCE_ID_FONT_UBUNTU_MONO_20
#define DATE_BOUNDS GRect(0, 120, 144, 30)

#define BATTERY_BOUNDS GRect(14, 50, 115, 5)
#define BATTERY_CORNERS GCornerNone

#endif